"""phase-1-day2: add submission fields to regulatory_decisions

Revision ID: 41de1fbac883
Revises: d2f6b579458c
Create Date: 2026-04-19 14:21:35.187159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41de1fbac883'
down_revision: Union[str, Sequence[str], None] = 'd2f6b579458c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('regulatory_decisions', sa.Column('submission_number', sa.String(length=16), nullable=True))
    op.add_column('regulatory_decisions', sa.Column('submission_type', sa.String(length=16), nullable=True))
    op.add_column('regulatory_decisions', sa.Column('review_priority', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('regulatory_decisions', 'review_priority')
    op.drop_column('regulatory_decisions', 'submission_type')
    op.drop_column('regulatory_decisions', 'submission_number')
    # ### end Alembic commands ###
