"""phase-0: initial schema (11 entities + junctions)

Revision ID: d2f6b579458c
Revises: 
Create Date: 2026-04-18 21:40:05.855581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd2f6b579458c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('url_hash', sa.String(length=64), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('source_name', sa.String(length=128), nullable=True),
    sa.Column('source_type', sa.String(length=64), nullable=True),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('publish_date', sa.Date(), nullable=True),
    sa.Column('credibility_tier', sa.String(length=32), nullable=True),
    sa.Column('cached_content', sa.Text(), nullable=True),
    sa.Column('cached_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('field_provenance', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_articles_publish_date'), 'articles', ['publish_date'], unique=False)
    op.create_index(op.f('ix_articles_url_hash'), 'articles', ['url_hash'], unique=True)
    op.create_table('companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sec_cik', sa.String(length=16), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('founded_date', sa.Date(), nullable=True),
    sa.Column('origin_narrative', sa.Text(), nullable=True),
    sa.Column('origin_narrative_zh', sa.Text(), nullable=True),
    sa.Column('origin_narrative_source_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('strategic_summary', sa.Text(), nullable=True),
    sa.Column('strategic_summary_zh', sa.Text(), nullable=True),
    sa.Column('strategic_summary_source_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('field_provenance', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=False)
    op.create_index(op.f('ix_companies_sec_cik'), 'companies', ['sec_cik'], unique=True)
    op.create_index(op.f('ix_companies_ticker'), 'companies', ['ticker'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('headline', sa.Text(), nullable=True),
    sa.Column('significance', sa.String(length=32), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('description_zh', sa.Text(), nullable=True),
    sa.Column('description_source_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('triggered_by', sa.UUID(), nullable=True),
    sa.Column('field_provenance', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['triggered_by'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_event_date'), 'events', ['event_date'], unique=False)
    op.create_index(op.f('ix_events_event_type'), 'events', ['event_type'], unique=False)
    op.create_index(op.f('ix_events_triggered_by'), 'events', ['triggered_by'], unique=False)
    op.create_table('indications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('efo_id', sa.String(length=32), nullable=True),
    sa.Column('mesh_id', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('name_zh', sa.String(length=256), nullable=True),
    sa.Column('aliases', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('treatment_landscape_summary', sa.Text(), nullable=True),
    sa.Column('treatment_landscape_summary_zh', sa.Text(), nullable=True),
    sa.Column('treatment_landscape_summary_source_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('field_provenance', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_indications_efo_id'), 'indications', ['efo_id'], unique=True)
    op.create_index(op.f('ix_indications_mesh_id'), 'indications', ['mesh_id'], unique=False)
    op.create_index(op.f('ix_indications_name'), 'indications', ['name'], unique=False)
    op.create_table('lessons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('title_zh', sa.String(length=256), nullable=True),
    sa.Column('lesson_type', sa.Enum('STRATEGIC_COMMERCIAL', 'SCIENTIFIC_MECHANISTIC', 'REGULATORY_PATHWAY', 'COMPETITIVE_DYNAMICS', 'CLINICAL_DEVELOPMENT', 'MANUFACTURING_CMC', 'MARKET_ACCESS_PRICING', name='lesson_type_kind'), nullable=False),
    sa.Column('pattern', sa.Text(), nullable=True),
    sa.Column('pattern_zh', sa.Text(), nullable=True),
    sa.Column('pattern_source_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('key_evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('limitations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('applicable_contexts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('applicable_to_landscapes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('human_reviewed', sa.Boolean(), nullable=False),
    sa.Column('reviewed_by', sa.String(length=64), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('field_provenance', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('targets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('uniprot_id', sa.String(length=32), nullable=True),
    sa.Column('ensembl_id', sa.String(length=32), nullable=True),
    sa.Column('gene_symbol', sa.String(length=64), nullable=True),
    sa.Column('approved_name', sa.String(length=512), nullable=True),
    sa.Column('biotype', sa.String(length=64), nullable=True),
    sa.Column('biology_summary', sa.Text(), nullable=True),
    sa.Column('biology_summary_zh', sa.Text(), nullable=True),
    sa.Column('biology_summary_source_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('validation_history', sa.Text(), nullable=True),
    sa.Column('validation_history_zh', sa.Text(), nullable=True),
    sa.Column('validation_history_source_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('competitive_landscape_summary', sa.Text(), nullable=True),
    sa.Column('competitive_landscape_summary_zh', sa.Text(), nullable=True),
    sa.Column('competitive_landscape_summary_source_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('pathway_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('go_molecular_function', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('go_biological_process', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('go_cellular_component', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('field_provenance', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_targets_ensembl_id'), 'targets', ['ensembl_id'], unique=True)
    op.create_index(op.f('ix_targets_gene_symbol'), 'targets', ['gene_symbol'], unique=False)
    op.create_index(op.f('ix_targets_uniprot_id'), 'targets', ['uniprot_id'], unique=True)
    op.create_table('claims',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('claim_type', sa.Enum('VERIFIED_FACT', 'ATTRIBUTED_ANALYSIS', 'PREDICTION', 'OPINION', 'DISPUTED', name='claim_type_kind'), nullable=False),
    sa.Column('evidence_basis', sa.String(length=128), nullable=True),
    sa.Column('confidence', sa.String(length=16), nullable=True),
    sa.Column('article_id', sa.UUID(), nullable=True),
    sa.Column('entities_mentioned', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('field_provenance', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claims_article_id'), 'claims', ['article_id'], unique=False)
    op.create_table('drugs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('drugbank_id', sa.String(length=32), nullable=True),
    sa.Column('chembl_id', sa.String(length=32), nullable=True),
    sa.Column('generic_name', sa.String(length=256), nullable=False),
    sa.Column('brand_names', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('aliases', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('inn', sa.String(length=256), nullable=True),
    sa.Column('modality', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('max_phase', sa.String(length=32), nullable=True),
    sa.Column('first_approval_date', sa.Date(), nullable=True),
    sa.Column('mechanism_of_action', sa.Text(), nullable=True),
    sa.Column('mechanism_of_action_zh', sa.Text(), nullable=True),
    sa.Column('mechanism_of_action_source_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('discovery_narrative', sa.Text(), nullable=True),
    sa.Column('discovery_narrative_zh', sa.Text(), nullable=True),
    sa.Column('discovery_narrative_source_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('revenue_peak_usd', sa.BigInteger(), nullable=True),
    sa.Column('revenue_peak_year', sa.Integer(), nullable=True),
    sa.Column('cumulative_revenue_usd', sa.BigInteger(), nullable=True),
    sa.Column('originator_id', sa.UUID(), nullable=True),
    sa.Column('field_provenance', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['originator_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drugs_chembl_id'), 'drugs', ['chembl_id'], unique=True)
    op.create_index(op.f('ix_drugs_drugbank_id'), 'drugs', ['drugbank_id'], unique=True)
    op.create_index(op.f('ix_drugs_generic_name'), 'drugs', ['generic_name'], unique=False)
    op.create_index(op.f('ix_drugs_originator_id'), 'drugs', ['originator_id'], unique=False)
    op.create_table('entity_lesson_link',
    sa.Column('lesson_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('lesson_id', 'entity_type', 'entity_id')
    )
    op.create_table('event_entity_link',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id', 'entity_type', 'entity_id')
    )
    op.create_table('target_indication_link',
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('indication_id', sa.UUID(), nullable=False),
    sa.Column('association_score', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['indication_id'], ['indications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('target_id', 'indication_id')
    )
    op.create_table('clinical_trials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nct_id', sa.String(length=16), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('phase', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('enrollment', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('completion_date', sa.Date(), nullable=True),
    sa.Column('primary_outcomes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('secondary_outcomes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('drug_id', sa.UUID(), nullable=True),
    sa.Column('sponsor_id', sa.UUID(), nullable=True),
    sa.Column('results_summary', sa.Text(), nullable=True),
    sa.Column('results_summary_zh', sa.Text(), nullable=True),
    sa.Column('results_summary_source_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('field_provenance', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['drug_id'], ['drugs.id'], ),
    sa.ForeignKeyConstraint(['sponsor_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinical_trials_drug_id'), 'clinical_trials', ['drug_id'], unique=False)
    op.create_index(op.f('ix_clinical_trials_nct_id'), 'clinical_trials', ['nct_id'], unique=True)
    op.create_index(op.f('ix_clinical_trials_sponsor_id'), 'clinical_trials', ['sponsor_id'], unique=False)
    op.create_table('drug_indication_link',
    sa.Column('drug_id', sa.UUID(), nullable=False),
    sa.Column('indication_id', sa.UUID(), nullable=False),
    sa.Column('max_phase', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['drug_id'], ['drugs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['indication_id'], ['indications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('drug_id', 'indication_id')
    )
    op.create_table('drug_target_link',
    sa.Column('drug_id', sa.UUID(), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['drug_id'], ['drugs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('drug_id', 'target_id')
    )
    op.create_table('entity_claim_link',
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('claim_id', 'entity_type', 'entity_id')
    )
    op.create_table('patents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patent_number', sa.String(length=32), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('filing_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('source_register', sa.Enum('ORANGE_BOOK', 'PURPLE_BOOK', 'USPTO_MANUAL', 'LITIGATION', 'ARTICLE_CITATION', name='patent_source_register'), nullable=False),
    sa.Column('nda_number', sa.String(length=32), nullable=True),
    sa.Column('patent_linkage_type', sa.String(length=64), nullable=True),
    sa.Column('bla_number', sa.String(length=32), nullable=True),
    sa.Column('reference_product_exclusivity_end', sa.Date(), nullable=True),
    sa.Column('uspto_application_number', sa.String(length=32), nullable=True),
    sa.Column('litigation_history', sa.Text(), nullable=True),
    sa.Column('litigation_history_zh', sa.Text(), nullable=True),
    sa.Column('litigation_history_source_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('drug_id', sa.UUID(), nullable=True),
    sa.Column('field_provenance', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['drug_id'], ['drugs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patents_drug_id'), 'patents', ['drug_id'], unique=False)
    op.create_index(op.f('ix_patents_expiry_date'), 'patents', ['expiry_date'], unique=False)
    op.create_index(op.f('ix_patents_patent_number'), 'patents', ['patent_number'], unique=False)
    op.create_table('regulatory_decisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bla_number', sa.String(length=32), nullable=True),
    sa.Column('nda_number', sa.String(length=32), nullable=True),
    sa.Column('application_number', sa.String(length=64), nullable=True),
    sa.Column('jurisdiction', sa.String(length=8), nullable=False),
    sa.Column('action_type', sa.String(length=64), nullable=False),
    sa.Column('decision_date', sa.Date(), nullable=True),
    sa.Column('indication_text', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('review_documents', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('drug_id', sa.UUID(), nullable=True),
    sa.Column('field_provenance', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['drug_id'], ['drugs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regulatory_decisions_application_number'), 'regulatory_decisions', ['application_number'], unique=False)
    op.create_index(op.f('ix_regulatory_decisions_bla_number'), 'regulatory_decisions', ['bla_number'], unique=False)
    op.create_index(op.f('ix_regulatory_decisions_decision_date'), 'regulatory_decisions', ['decision_date'], unique=False)
    op.create_index(op.f('ix_regulatory_decisions_drug_id'), 'regulatory_decisions', ['drug_id'], unique=False)
    op.create_index(op.f('ix_regulatory_decisions_nda_number'), 'regulatory_decisions', ['nda_number'], unique=False)
    # ### end Alembic commands ###

    # ADR-0002: entity_relationships VIEW unions junction + FK-based edges.
    # Recursive-CTE graph queries read from this view (design doc §8.3).
    # Amend this DDL every time a new junction table is added.
    op.execute("""
    CREATE VIEW entity_relationships AS
    SELECT 'drug'::text AS source_type, drug_id AS source_id,
           'target'::text AS target_type, target_id AS target_id,
           'hits'::text AS relationship_type
      FROM drug_target_link
    UNION ALL
    SELECT 'target', target_id, 'drug', drug_id, 'hit_by' FROM drug_target_link
    UNION ALL
    SELECT 'drug', drug_id, 'indication', indication_id, 'treats' FROM drug_indication_link
    UNION ALL
    SELECT 'indication', indication_id, 'drug', drug_id, 'treated_by' FROM drug_indication_link
    UNION ALL
    SELECT 'target', target_id, 'indication', indication_id, 'associated_with' FROM target_indication_link
    UNION ALL
    SELECT 'indication', indication_id, 'target', target_id, 'associated_with' FROM target_indication_link
    UNION ALL
    SELECT 'drug', originator_id, 'company', id, 'developed_by' FROM drugs WHERE originator_id IS NOT NULL
    UNION ALL
    SELECT 'company', id, 'drug', originator_id, 'originated' FROM drugs WHERE originator_id IS NOT NULL
    UNION ALL
    SELECT 'clinical_trial', id, 'drug', drug_id, 'tests' FROM clinical_trials WHERE drug_id IS NOT NULL
    UNION ALL
    SELECT 'drug', drug_id, 'clinical_trial', id, 'tested_in' FROM clinical_trials WHERE drug_id IS NOT NULL
    UNION ALL
    SELECT 'clinical_trial', id, 'company', sponsor_id, 'sponsored_by' FROM clinical_trials WHERE sponsor_id IS NOT NULL
    UNION ALL
    SELECT 'company', sponsor_id, 'clinical_trial', id, 'sponsors' FROM clinical_trials WHERE sponsor_id IS NOT NULL
    UNION ALL
    SELECT 'regulatory_decision', id, 'drug', drug_id, 'decides_on' FROM regulatory_decisions WHERE drug_id IS NOT NULL
    UNION ALL
    SELECT 'drug', drug_id, 'regulatory_decision', id, 'has_decision' FROM regulatory_decisions WHERE drug_id IS NOT NULL
    UNION ALL
    SELECT 'patent', id, 'drug', drug_id, 'protects' FROM patents WHERE drug_id IS NOT NULL
    UNION ALL
    SELECT 'drug', drug_id, 'patent', id, 'protected_by' FROM patents WHERE drug_id IS NOT NULL
    UNION ALL
    SELECT 'event', triggered_by, 'event', id, 'triggers' FROM events WHERE triggered_by IS NOT NULL
    UNION ALL
    SELECT 'event', id, 'event', triggered_by, 'triggered_by' FROM events WHERE triggered_by IS NOT NULL
    UNION ALL
    SELECT entity_type, entity_id, 'claim', claim_id, 'has_claim' FROM entity_claim_link
    UNION ALL
    SELECT 'claim', claim_id, entity_type, entity_id, 'about' FROM entity_claim_link
    UNION ALL
    SELECT entity_type, entity_id, 'lesson', lesson_id, 'teaches' FROM entity_lesson_link
    UNION ALL
    SELECT 'lesson', lesson_id, entity_type, entity_id, 'applies_to' FROM entity_lesson_link
    UNION ALL
    SELECT 'event', event_id, entity_type, entity_id, 'involves' FROM event_entity_link
    UNION ALL
    SELECT entity_type, entity_id, 'event', event_id, 'participates_in' FROM event_entity_link;
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # Drop VIEW first (depends on junction tables)
    op.execute("DROP VIEW IF EXISTS entity_relationships;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_regulatory_decisions_nda_number'), table_name='regulatory_decisions')
    op.drop_index(op.f('ix_regulatory_decisions_drug_id'), table_name='regulatory_decisions')
    op.drop_index(op.f('ix_regulatory_decisions_decision_date'), table_name='regulatory_decisions')
    op.drop_index(op.f('ix_regulatory_decisions_bla_number'), table_name='regulatory_decisions')
    op.drop_index(op.f('ix_regulatory_decisions_application_number'), table_name='regulatory_decisions')
    op.drop_table('regulatory_decisions')
    op.drop_index(op.f('ix_patents_patent_number'), table_name='patents')
    op.drop_index(op.f('ix_patents_expiry_date'), table_name='patents')
    op.drop_index(op.f('ix_patents_drug_id'), table_name='patents')
    op.drop_table('patents')
    op.drop_table('entity_claim_link')
    op.drop_table('drug_target_link')
    op.drop_table('drug_indication_link')
    op.drop_index(op.f('ix_clinical_trials_sponsor_id'), table_name='clinical_trials')
    op.drop_index(op.f('ix_clinical_trials_nct_id'), table_name='clinical_trials')
    op.drop_index(op.f('ix_clinical_trials_drug_id'), table_name='clinical_trials')
    op.drop_table('clinical_trials')
    op.drop_table('target_indication_link')
    op.drop_table('event_entity_link')
    op.drop_table('entity_lesson_link')
    op.drop_index(op.f('ix_drugs_originator_id'), table_name='drugs')
    op.drop_index(op.f('ix_drugs_generic_name'), table_name='drugs')
    op.drop_index(op.f('ix_drugs_drugbank_id'), table_name='drugs')
    op.drop_index(op.f('ix_drugs_chembl_id'), table_name='drugs')
    op.drop_table('drugs')
    op.drop_index(op.f('ix_claims_article_id'), table_name='claims')
    op.drop_table('claims')
    op.drop_index(op.f('ix_targets_uniprot_id'), table_name='targets')
    op.drop_index(op.f('ix_targets_gene_symbol'), table_name='targets')
    op.drop_index(op.f('ix_targets_ensembl_id'), table_name='targets')
    op.drop_table('targets')
    op.drop_table('lessons')
    op.drop_index(op.f('ix_indications_name'), table_name='indications')
    op.drop_index(op.f('ix_indications_mesh_id'), table_name='indications')
    op.drop_index(op.f('ix_indications_efo_id'), table_name='indications')
    op.drop_table('indications')
    op.drop_index(op.f('ix_events_triggered_by'), table_name='events')
    op.drop_index(op.f('ix_events_event_type'), table_name='events')
    op.drop_index(op.f('ix_events_event_date'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_companies_ticker'), table_name='companies')
    op.drop_index(op.f('ix_companies_sec_cik'), table_name='companies')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_articles_url_hash'), table_name='articles')
    op.drop_index(op.f('ix_articles_publish_date'), table_name='articles')
    op.drop_table('articles')
    # ### end Alembic commands ###

    # PostgreSQL ENUM types don't auto-drop with their columns; do it explicitly
    # so upgrade/downgrade/upgrade cycles are idempotent.
    op.execute("DROP TYPE IF EXISTS patent_source_register CASCADE;")
    op.execute("DROP TYPE IF EXISTS claim_type_kind CASCADE;")
    op.execute("DROP TYPE IF EXISTS lesson_type_kind CASCADE;")
